---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kannel-logs
  labels:
    app: kannelgw
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kannel-spool
  labels:
    app: kannelgw
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smsbox-logs
  labels:
    app: smsbox
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
      
